name: 'Automation Changelog'
description: 'Update the changelog every time a PR is merged'
author: 'Team Devops'
inputs:
  changelog_file_name:
    required: false
    description: 'add changelog file name'
    default: 'CHANGELOG.md'
  changelog_new_log:
    required: true
    description: 'add new log'
  changelog_new_comments:
    required: false
    description: 'add new comments'
  log_find:
    required: true
    description: 'add the key where the log below will be added'
  comment_find:
    required: false
    description: 'add the key where the log below will be added'
  encoding:
    required: false
    description: 'add encoded read file'
    default: 'utf-8'
  repo_main:
    required: false
    description: 'Name main repository'
    default: 'heads/main'
  payload:
    required: false
    description: 'Paylod send slack message'
  max_logs:
    required: false
    description: 'add encoded read file'
    default: '5'
  create_release_with_brancher_history:
    required: false
    description: 'create brancher release using history brancher'
    default: "false"
  brancher_history_name:
    required: false
    description: 'Brancher history name'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'arrow-right-circle'  
  color: 'blue'
