name: Changelog Automation

on:
  push:
    branches:
      - main
      - release/**

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, 'Merge')"
    steps:
      - name: Checkout Github
        uses: actions/checkout@v3

      - name: Get Title PR
        id: get_message
        run: echo "::set-output name=MESSAGE::$(echo '${{github.event.head_commit.message}}' | tail -n 1)"

      - name: Update Changelog
        uses: ./
        with:
          changelog_new_log: ${{ steps.get_message.outputs.MESSAGE }}
          log_find: '## Alterações'

      - name: Commit Update Changelog
        run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          git add CHANGELOG.md
          git commit -m 'action: update changelog'
          echo "${GITHUB_REF#refs/heads/}"

      - name: Push Update Changelog
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
