name: Check dist/

concurrency:
  group: check-dist-${{ github.ref_name }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  check-dist:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'Merge') || github.event.pull_request.draft == false"

    steps:
      - name: Checkout Github
        uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Rebuild the dist/ directory
        run: |
          yarn build
          yarn package

      # If index.js was different than expected, upload the expected version as an artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/
