name: Check dist/

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  check-dist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Github
        uses: actions/checkout@v2

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Rebuild the dist/ directory
        run: |
          yarn build
          yarn package

      # If index.js was different than expected, upload the expected version as an artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/
