name: 'test lint and jest'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test-linter-jest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github
        uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: npm install

      - name: Run All
        run: npm run all
