name: 'test lint and jest'

concurrency:
  group: test-lint-${{ github.ref_name }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test-linter-jest:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'Merge') || github.event.pull_request.draft == false"

    steps:
      - name: Checkout Github
        uses: actions/checkout@v4.1.1

      - name: Set Node.js 16.x
        uses: actions/setup-node@v4
        with:
          node-version: 16.x

      - name: Install yarn
        run: npm install -g yarn

      - name: Install Dependencies
        run: yarn

      - name: Run All
        run: npm run all
