name: 'test lint and jest'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test-linter-jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
